from pathlib import Path
from typing import Any


def build_architecture_scratchpad_payload(
    *,
    repo_url: str,
    retrieval_strategy: str,
    selected_files: list[str],
    react_trace: list[dict[str, Any]],
    react_stop_reason: str,
    exploration_path: Path | None,
    exploration_artifact: dict[str, Any],
    synthesis_path: Path | None,
    synthesis_artifact: dict[str, Any],
    synthesis_loop_trace: list[dict[str, Any]],
    synthesis_stop_reason: str,
    validation_path: Path | None,
    validation_artifact: dict[str, Any],
    validation_loop_trace: list[dict[str, Any]],
    validation_stop_reason: str,
    step1_tokens: int,
    step2_tokens: int,
    two_step_total_tokens: int,
    summary_path: Path,
    structure_summary_path: Path,
    selected_files_path: Path,
    subagents_enabled: bool,
    budget_behavior: dict[str, Any],
) -> dict[str, Any]:
    return {
        "schema_version": "1.0",
        "repo": repo_url,
        "generated_by": "agent_classify.py",
        "contract": {
            "required_sections": ["exploration", "synthesis", "validation"],
            "optional_sections": ["react_trace"],
        },
        "architecture": {
            "retrieval_strategy": retrieval_strategy,
            "exploration": {
                "selected_files_count": len(selected_files),
                "selected_files": selected_files,
                "react_steps": len(react_trace),
                "react_stop_reason": react_stop_reason,
                "exploration_artifact_path": str(exploration_path) if exploration_path else None,
                "evidence_gaps": exploration_artifact["evidence_gaps"],
                "react_trace": react_trace,
            },
            "synthesis": {
                "selected_summary_path": str(summary_path),
                "structure_summary_path": str(structure_summary_path),
                "selected_files_path": str(selected_files_path),
                "synthesis_artifact_path": str(synthesis_path) if synthesis_path else None,
                "react_steps": len(synthesis_loop_trace),
                "react_stop_reason": synthesis_stop_reason,
                "subagents_enabled": subagents_enabled,
                "subagent_outputs": synthesis_artifact["subagent_outputs"],
                "abstraction": synthesis_artifact.get("abstraction_l2", {}),
                "transition_policy": synthesis_artifact.get("transition_policy", {}),
                "loop_checkpoint": synthesis_artifact.get("loop_checkpoint", {}),
                "react_trace": synthesis_loop_trace,
                "build_strategy_hypotheses": synthesis_artifact["build_strategy_hypotheses"],
                "risk_notes": synthesis_artifact["risk_notes"],
                "prompt_tokens": {
                    "step1_selection": step1_tokens,
                    "step2_classification": step2_tokens,
                    "two_step_total": two_step_total_tokens,
                },
                "budget_behavior": budget_behavior,
            },
            "validation": {
                "validation_artifact_path": str(validation_path) if validation_path else None,
                "react_steps": len(validation_loop_trace),
                "react_stop_reason": validation_stop_reason,
                "abstraction": validation_artifact.get("abstraction_l3", {}),
                "outcome_state": validation_artifact.get("outcome_state", "unknown"),
                "loop_checkpoint": validation_artifact.get("loop_checkpoint", {}),
                "react_trace": validation_loop_trace,
                "checks": validation_artifact["checks"],
                "warnings": validation_artifact["warnings"],
            },
        },
    }
